steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:ssr']
  # Install cloud functions
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['install']
  # Copy build to cloud functions
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['run', 'copy']
  # Deploy Hosting
  - name: 'gcr.io/rosfinex-d2aa4/firebase'
    args: ['deploy']